export const stockData = {
  ticker: "PYPL",
  name: "PayPal Holdings, Inc.",
  sector: "Financial Services",
  earningsDate: "Oct 31, 2024",
  watchlists: 18274,
  price: 81.65,
  change: 26.94,
  changePct: 50.0,
  priceTimestamp: "Aug 30, 2024 at 4:00 PM EDT, USD",
  sentimentBear: 18,
  sentimentBearCount: 2345,
  sentimentBull: 78,
  sentimentBullCount: 11450,
  performance: {
    price: 72.61,
    d1: 0.05,
    d5: 1.02,
    m1: 13.17,
    m6: 20.22,
    ytd: 17.94,
    y1: 14.21,
    y5: -33.58,
    all: 97.3,
  },
};

export const keyStats = {
  basic: [
    { label: "Market Cap", value: "$66.17B" },
    { label: "Enterprise Value", value: "$71.34B" },
    { label: "Shares Outstanding", value: "1,022.33M" },
    { label: "1y Target Est", value: "77.74" },
    { label: "Fair Value", value: "$114.76" },
    { label: "Earnings Date", value: "Oct 31, 2024" },
    { label: "Beta (5Y Monthly)", value: "1.42" },
    { label: "Employees", value: "27,200" },
  ],
  valuation: [
    { label: "P/E Ratio", value: "15.98" },
    { label: "Trailing P/E", value: "15.98" },
    { label: "Forward P/E", value: "15.98" },
    { label: "P/S Ratio", value: "2.29" },
    { label: "Price/Book Ratio", value: "3.23" },
    { label: "Price/FCF Ratio", value: "13.75" },
    { label: "EV/EBITDA", value: "12.57" },
    { label: "EV/Sales", value: "2.39" },
    { label: "Cash/Debt", value: "1.4" },
  ],
  revenue: [
    { label: "Revenue", value: "$30.43B" },
    { label: "Gross Profit", value: "$11.96" },
    { label: "Operation Income", value: "$5.19" },
    { label: "Net Income", value: "$4.33" },
    { label: "EBITDA", value: "$5.89" },
    { label: "EPS", value: "$3.97" },
  ],
  margins: [
    { label: "Gross Margin", value: "39.32%" },
    { label: "Operation Margin", value: "17.08%" },
    { label: "EBITDA Margin", value: "19.36%" },
    { label: "Pre-Tax Margin", value: "18.32%" },
    { label: "Net Margin", value: "14.26%" },
    { label: "Free Cash Flow", value: "21.6%" },
  ],
  growth: [
    { label: "Quarterly Revenue (YoY)", value: "8.21%" },
    { label: "Revenue (3Y)", value: "8.21%" },
    { label: "Quarterly EPS (YoY)", value: "17.39%" },
    { label: "EPS (3Y)", value: "17.39%" },
  ],
  assets: [
    { label: "Total Assets", value: "$83.34B" },
    { label: "Cash on Hand", value: "$14.31B" },
    { label: "Long Term Debt", value: "$9.68B" },
    { label: "Total Liabilities", value: "$62.64B" },
    { label: "Share Holder Equity", value: "$20.70B" },
    { label: "Debt/Equity", value: "62.84%" },
  ],
  returns: [
    { label: "Return on Equity (ROE)", value: "22.03%" },
    { label: "Return on Assets (ROA)", value: "4.19%" },
    { label: "Return on Capital Employed (ROCE)", value: "13.4%" },
    { label: "Return on Investments (ROI)", value: "14.5%" },
  ],
  dividends: [
    { label: "Yield", value: "-" },
    { label: "Payout", value: "-" },
  ],
  risk: [
    { label: "Beta (5Y)", value: "1.434" },
    { label: "Max Drawdown (5Y)", value: "83.76%" },
  ],
};
