import type { ChartingSeriesPoint } from "@/lib/market/charting-series-types";

type FinancialsMetricKind = "usd" | "eps" | "shares" | "percent" | "multiple" | "ratio";

/** Extra charting metric ids used by Financials table row modals (not all appear in Charting dropdown). */
export const FINANCIALS_EXTRA_CHARTING_METRIC_IDS = [
  "cost_of_revenue",
  "sga",
  "research_development",
  "other_operating_expense",
  "total_operating_expenses",
  "pretax_income",
  "net_income_yoy",
  "shares_outstanding_yoy",
  "eps_basic",
  "fcf_per_share",
  "dividends_per_share",
  "dividends_per_share_yoy",
  "effective_tax_rate",
  "cash_equivalents",
  "short_term_investments",
  "cash_and_short_term_investments",
  "accounts_receivable",
  "other_receivables",
  "other_current_assets",
  "total_current_assets",
  "property_plant_equipment",
  "goodwill",
  "intangible_assets",
  "long_term_investments",
  "other_non_current_assets",
  "accounts_payable",
  "accrued_liabilities",
  "other_current_liabilities",
  "total_current_liabilities",
  "non_current_liabilities",
  "treasury_stock",
  "additional_paid_in_capital",
  "total_debt",
  "net_cash",
  "book_value",
  "tangible_book_value",
  "depreciation_amortization",
  "stock_based_compensation",
  "other_non_cash_adjustments",
  "change_in_receivables",
  "change_in_accounts_payable",
  "change_in_other_operating",
  "operating_cash_flow",
  "operating_cash_flow_yoy",
  "capital_expenditures",
  "sale_of_ppe",
  "purchases_of_investments",
  "proceeds_from_investments",
  "payments_for_acquisitions",
  "proceeds_from_divestitures",
  "investments_cash_flow",
  "other_investing_cash_flow",
  "investing_cash_flow",
  "short_term_debt_issued",
  "short_term_debt_repaid",
  "long_term_debt_issued",
  "long_term_debt_repaid",
  "net_debt_issued",
  "issuance_common_stock",
  "repurchase_common_stock",
  "net_common_stock",
  "dividends_paid",
  "other_financing_cash_flow",
  "financing_cash_flow",
  "exchange_rate_effect",
  "change_in_cash",
  "free_cash_flow_yoy",
  "levered_free_cash_flow",
  "unlevered_free_cash_flow",
  "market_cap_yoy",
  "peg_ratio",
  "price_to_tangible_book",
  "price_ocf",
  "ev_to_ebit",
  "ev_to_fcf",
  "debt_to_ebitda",
  "debt_to_fcf",
  "net_debt_to_equity",
  "net_debt_to_ebitda",
  "net_debt_to_fcf",
  "asset_turnover",
  "quick_ratio",
  "current_ratio",
  "return_on_invested_capital",
  "earnings_yield",
  "fcf_yield",
] as const;

export type FinancialsExtraChartingMetricId = (typeof FINANCIALS_EXTRA_CHARTING_METRIC_IDS)[number];

export const FINANCIALS_EXTRA_CHARTING_METRIC_FIELD: Record<
  FinancialsExtraChartingMetricId,
  keyof ChartingSeriesPoint
> = {
  cost_of_revenue: "revenue",
  sga: "sga",
  research_development: "researchAndDevelopment",
  other_operating_expense: "otherOperatingExpense",
  total_operating_expenses: "totalOperatingExpenses",
  pretax_income: "incomeBeforeTax",
  net_income_yoy: "netIncomeYoy",
  shares_outstanding_yoy: "sharesOutstandingYoy",
  eps_basic: "epsBasic",
  fcf_per_share: "fcfPerShare",
  dividends_per_share: "dividendsPerShare",
  dividends_per_share_yoy: "dividendsPerShareYoy",
  effective_tax_rate: "effectiveTaxRate",
  cash_equivalents: "cashEquivalents",
  short_term_investments: "shortTermInvestments",
  cash_and_short_term_investments: "cashAndShortTermInvestments",
  accounts_receivable: "netReceivables",
  other_receivables: "otherReceivables",
  other_current_assets: "otherCurrentAssets",
  total_current_assets: "totalCurrentAssets",
  property_plant_equipment: "propertyPlantEquipmentNet",
  goodwill: "goodwill",
  intangible_assets: "intangibleAssets",
  long_term_investments: "longTermInvestments",
  other_non_current_assets: "otherNonCurrentAssets",
  accounts_payable: "accountsPayable",
  accrued_liabilities: "accruedLiabilities",
  other_current_liabilities: "otherCurrentLiabilities",
  total_current_liabilities: "currentLiabilities",
  non_current_liabilities: "nonCurrentLiabilities",
  treasury_stock: "treasuryStock",
  additional_paid_in_capital: "additionalPaidInCapital",
  total_debt: "totalDebt",
  net_cash: "netDebt",
  book_value: "bookValue",
  tangible_book_value: "tangibleBookValue",
  depreciation_amortization: "cfDepreciationAmortization",
  stock_based_compensation: "cfStockBasedCompensation",
  other_non_cash_adjustments: "cfOtherNonCashItems",
  change_in_receivables: "cfChangeInReceivables",
  change_in_accounts_payable: "cfChangeInAccountsPayable",
  change_in_other_operating: "cfChangeInOtherOperating",
  operating_cash_flow: "operatingCashFlow",
  operating_cash_flow_yoy: "operatingCashFlowYoy",
  capital_expenditures: "capitalExpenditures",
  sale_of_ppe: "cfSaleOfPpe",
  purchases_of_investments: "cfPurchasesOfInvestments",
  proceeds_from_investments: "cfProceedsFromInvestments",
  payments_for_acquisitions: "cfPaymentsForAcquisitions",
  proceeds_from_divestitures: "cfProceedsFromDivestitures",
  investments_cash_flow: "cfInvestments",
  other_investing_cash_flow: "cfOtherInvestingCashFlow",
  investing_cash_flow: "investingCashFlow",
  short_term_debt_issued: "cfShortTermDebtIssued",
  short_term_debt_repaid: "cfShortTermDebtRepaid",
  long_term_debt_issued: "cfLongTermDebtIssued",
  long_term_debt_repaid: "cfLongTermDebtRepaid",
  net_debt_issued: "cfNetDebtIssued",
  issuance_common_stock: "cfIssuanceOfCommonStock",
  repurchase_common_stock: "cfRepurchaseOfCommonStock",
  net_common_stock: "cfNetCommonStock",
  dividends_paid: "dividendsPaid",
  other_financing_cash_flow: "cfOtherFinancingCashFlow",
  financing_cash_flow: "financingCashFlow",
  exchange_rate_effect: "cfExchangeRateEffect",
  change_in_cash: "changeInCash",
  free_cash_flow_yoy: "freeCashFlowYoy",
  levered_free_cash_flow: "leveredFreeCashFlow",
  unlevered_free_cash_flow: "unleveredFreeCashFlow",
  market_cap_yoy: "marketCapYoy",
  peg_ratio: "pegRatio",
  price_to_tangible_book: "priceToTangibleBook",
  price_ocf: "priceOcf",
  ev_to_ebit: "evToEbit",
  ev_to_fcf: "evToFcf",
  debt_to_ebitda: "debtToEbitda",
  debt_to_fcf: "debtToFcf",
  net_debt_to_equity: "netDebtToEquity",
  net_debt_to_ebitda: "netDebtToEbitda",
  net_debt_to_fcf: "netDebtToFcf",
  asset_turnover: "assetTurnover",
  quick_ratio: "quickRatio",
  current_ratio: "currentRatio",
  return_on_invested_capital: "returnOnInvestedCapital",
  earnings_yield: "earningsYield",
  fcf_yield: "fcfYield",
};

export const FINANCIALS_EXTRA_CHARTING_METRIC_LABEL: Record<FinancialsExtraChartingMetricId, string> = {
  cost_of_revenue: "Cost of revenue",
  sga: "Selling, General & Admin",
  research_development: "Research & Development",
  other_operating_expense: "Other Operating Expenses",
  total_operating_expenses: "Total Operating Expenses",
  pretax_income: "Pretax Income",
  net_income_yoy: "Net Income Growth",
  shares_outstanding_yoy: "Shares Change",
  eps_basic: "EPS (Basic)",
  fcf_per_share: "Free Cash Flow Per Share",
  dividends_per_share: "Dividends Per Share",
  dividends_per_share_yoy: "Dividend Growth",
  effective_tax_rate: "Effective Tax Rate",
  cash_equivalents: "Cash & Equivalents",
  short_term_investments: "Short-Term Investments",
  cash_and_short_term_investments: "Cash & Short-Term Investments",
  accounts_receivable: "Accounts Receivable",
  other_receivables: "Other Receivables",
  other_current_assets: "Other Current Assets",
  total_current_assets: "Total Current Assets",
  property_plant_equipment: "Net Property, Plant & Equipment",
  goodwill: "Goodwill",
  intangible_assets: "Other Intangible Assets",
  long_term_investments: "Long-Term Investments",
  other_non_current_assets: "Other Long-Term Assets",
  accounts_payable: "Accounts Payable",
  accrued_liabilities: "Accrued Expenses",
  other_current_liabilities: "Other Current Liabilities",
  total_current_liabilities: "Total Current Liabilities",
  non_current_liabilities: "Long-Term Liabilities",
  treasury_stock: "Treasury Stock",
  additional_paid_in_capital: "Additional Paid-in Capital",
  total_debt: "Total Debt",
  net_cash: "Net Cash (Debt)",
  book_value: "Book Value",
  tangible_book_value: "Tangible Book Value",
  depreciation_amortization: "Depreciation & Amortization",
  stock_based_compensation: "Stock-Based Compensation",
  other_non_cash_adjustments: "Other Adjustments",
  change_in_receivables: "Change in Receivables",
  change_in_accounts_payable: "Changes in Accounts Payable",
  change_in_other_operating: "Changes in Other Operating Activities",
  operating_cash_flow: "Operating Cash Flow",
  operating_cash_flow_yoy: "Operating Cash Flow Growth",
  capital_expenditures: "Capital Expenditures",
  sale_of_ppe: "Sale of Property, Plant & Equipment",
  purchases_of_investments: "Purchases of Investments",
  proceeds_from_investments: "Proceeds from Sale of Investments",
  payments_for_acquisitions: "Payments for Business Acquisitions",
  proceeds_from_divestitures: "Proceeds from Business Divestitures",
  investments_cash_flow: "Investments",
  other_investing_cash_flow: "Other Investing Activities",
  investing_cash_flow: "Investing Cash Flow",
  short_term_debt_issued: "Short-Term Debt Issued",
  short_term_debt_repaid: "Short-Term Debt Repaid",
  long_term_debt_issued: "Long-Term Debt Issued",
  long_term_debt_repaid: "Long-Term Debt Repaid",
  net_debt_issued: "Net Long-Term Debt Issued (Repaid)",
  issuance_common_stock: "Issuance of Common Stock",
  repurchase_common_stock: "Repurchase of Common Stock",
  net_common_stock: "Net Common Stock Issued (Repurchased)",
  dividends_paid: "Common Dividends Paid",
  other_financing_cash_flow: "Other Financing Activities",
  financing_cash_flow: "Financing Cash Flow",
  exchange_rate_effect: "Effect of Exchange Rate Changes",
  change_in_cash: "Net Change in Cash",
  free_cash_flow_yoy: "Free Cash Flow Growth",
  levered_free_cash_flow: "Levered Free Cash Flow",
  unlevered_free_cash_flow: "Unlevered Free Cash Flow",
  market_cap_yoy: "Market Cap Growth",
  peg_ratio: "PEG Ratio",
  price_to_tangible_book: "P/TBV Ratio",
  price_ocf: "P/OCF Ratio",
  ev_to_ebit: "EV/EBIT Ratio",
  ev_to_fcf: "EV/FCF Ratio",
  debt_to_ebitda: "Debt / EBITDA Ratio",
  debt_to_fcf: "Debt / FCF Ratio",
  net_debt_to_equity: "Net Debt / Equity Ratio",
  net_debt_to_ebitda: "Net Debt / EBITDA Ratio",
  net_debt_to_fcf: "Net Debt / FCF Ratio",
  asset_turnover: "Asset Turnover",
  quick_ratio: "Quick Ratio",
  current_ratio: "Current Ratio",
  return_on_invested_capital: "Return on Invested Capital (ROIC)",
  earnings_yield: "Earnings Yield",
  fcf_yield: "FCF Yield",
};

export const FINANCIALS_EXTRA_CHARTING_METRIC_KIND: Record<FinancialsExtraChartingMetricId, FinancialsMetricKind> = {
  cost_of_revenue: "usd",
  sga: "usd",
  research_development: "usd",
  other_operating_expense: "usd",
  total_operating_expenses: "usd",
  pretax_income: "usd",
  net_income_yoy: "percent",
  shares_outstanding_yoy: "percent",
  eps_basic: "eps",
  fcf_per_share: "eps",
  dividends_per_share: "eps",
  dividends_per_share_yoy: "percent",
  effective_tax_rate: "percent",
  cash_equivalents: "usd",
  short_term_investments: "usd",
  cash_and_short_term_investments: "usd",
  accounts_receivable: "usd",
  other_receivables: "usd",
  other_current_assets: "usd",
  total_current_assets: "usd",
  property_plant_equipment: "usd",
  goodwill: "usd",
  intangible_assets: "usd",
  long_term_investments: "usd",
  other_non_current_assets: "usd",
  accounts_payable: "usd",
  accrued_liabilities: "usd",
  other_current_liabilities: "usd",
  total_current_liabilities: "usd",
  non_current_liabilities: "usd",
  treasury_stock: "usd",
  additional_paid_in_capital: "usd",
  total_debt: "usd",
  net_cash: "usd",
  book_value: "usd",
  tangible_book_value: "usd",
  depreciation_amortization: "usd",
  stock_based_compensation: "usd",
  other_non_cash_adjustments: "usd",
  change_in_receivables: "usd",
  change_in_accounts_payable: "usd",
  change_in_other_operating: "usd",
  operating_cash_flow: "usd",
  operating_cash_flow_yoy: "percent",
  capital_expenditures: "usd",
  sale_of_ppe: "usd",
  purchases_of_investments: "usd",
  proceeds_from_investments: "usd",
  payments_for_acquisitions: "usd",
  proceeds_from_divestitures: "usd",
  investments_cash_flow: "usd",
  other_investing_cash_flow: "usd",
  investing_cash_flow: "usd",
  short_term_debt_issued: "usd",
  short_term_debt_repaid: "usd",
  long_term_debt_issued: "usd",
  long_term_debt_repaid: "usd",
  net_debt_issued: "usd",
  issuance_common_stock: "usd",
  repurchase_common_stock: "usd",
  net_common_stock: "usd",
  dividends_paid: "usd",
  other_financing_cash_flow: "usd",
  financing_cash_flow: "usd",
  exchange_rate_effect: "usd",
  change_in_cash: "usd",
  free_cash_flow_yoy: "percent",
  levered_free_cash_flow: "usd",
  unlevered_free_cash_flow: "usd",
  market_cap_yoy: "percent",
  peg_ratio: "multiple",
  price_to_tangible_book: "multiple",
  price_ocf: "multiple",
  ev_to_ebit: "multiple",
  ev_to_fcf: "multiple",
  debt_to_ebitda: "multiple",
  debt_to_fcf: "multiple",
  net_debt_to_equity: "multiple",
  net_debt_to_ebitda: "multiple",
  net_debt_to_fcf: "multiple",
  asset_turnover: "ratio",
  quick_ratio: "ratio",
  current_ratio: "ratio",
  return_on_invested_capital: "percent",
  earnings_yield: "percent",
  fcf_yield: "percent",
};

/** Computed readers for metrics that are not a single stored field (or need sign flip). */
export function readFinancialsExtraChartingMetricValue(
  row: ChartingSeriesPoint,
  id: FinancialsExtraChartingMetricId,
): number | null {
  if (id === "cost_of_revenue") {
    if (row.revenue == null || row.grossProfit == null) return null;
    return row.revenue - row.grossProfit;
  }
  if (id === "cash_equivalents") {
    const v = row.cashEquivalents ?? row.cashOnHand;
    return typeof v === "number" && Number.isFinite(v) ? v : null;
  }
  if (id === "net_cash") {
    const cash = row.cashAndShortTermInvestments ?? row.cashEquivalents ?? row.cashOnHand;
    const debt = row.totalDebt;
    if (cash == null && debt == null) return null;
    return (cash ?? 0) - (debt ?? 0);
  }
  const k = FINANCIALS_EXTRA_CHARTING_METRIC_FIELD[id];
  const v = row[k];
  return typeof v === "number" && Number.isFinite(v) ? v : null;
}

export function isFinancialsExtraChartingMetricId(s: string): s is FinancialsExtraChartingMetricId {
  return (FINANCIALS_EXTRA_CHARTING_METRIC_IDS as readonly string[]).includes(s);
}
