import type { FC, SVGProps } from "react";

export type AppIcon = FC<SVGProps<SVGSVGElement> & { size?: number; color?: string }>;

/** Sidebar / mobile nav (native Untitled names). */
export {
  BarChartSquare01,
  BookOpen01,
  Briefcase01,
  Calendar,
  Globe01,
  Globe04,
  Grid01,
  IntersectCircle,
  Rows01,
  Rows03,
  Users01,
  UsersPlus,
} from "@untitledui-pro/icons/line";

/**
 * App-wide icons with Lucide-compatible aliases for incremental migration.
 * Import from `@/lib/icons` instead of `lucide-react`.
 */
export {
  ArrowDown,
  ArrowUp,
  Bank as Landmark,
  BarChart03 as BarChart3,
  BarLineChart as FileBarChart,
  Bell01 as Bell,
  BellMinus,
  BellPlus,
  Briefcase01 as Briefcase,
  Calendar as CalendarDays,
  Calendar as CalendarIcon,
  Check,
  CheckCircle as CircleCheck,
  Clock,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Coins01 as Coins,
  Compass,
  CreditCard01 as CreditCard,
  Dataflow03 as ChartSpline,
  DotsGrid as GripVertical,
  DotsHorizontal as MoreHorizontal,
  Download01 as Download,
  Eye,
  EyeOff,
  File02 as FileText,
  FileCode01 as FileCode,
  FileSearch01 as FileSearch,
  FilterLines as Filter,
  FlipBackward as RotateCcw,
  GitMerge,
  Globe01 as Globe,
  HelpCircle as CircleQuestionMark,
  InfoCircle as Info,
  Laptop01 as Laptop,
  LayersTwo01 as Layers2,
  LayoutLeft as PanelLeft,
  LayoutRight as PanelLeftOpen,
  LineChartUp01 as LineChart,
  LinkExternal01 as ExternalLink,
  List as LayoutList,
  Loading01 as Loader2,
  Lock01 as Lock,
  LogOut01 as LogOut,
  Maximize01 as Maximize2,
  Menu01 as Menu,
  MessageCircle01 as MessageCircle,
  MessageSquare02 as MessagesSquare,
  Minimize01 as Minimize2,
  Minus,
  Pencil01 as Pencil,
  Phone01 as Smartphone,
  PieChart01 as PieChart,
  PlayCircle,
  Plus,
  PresentationChart01 as Presentation,
  RefreshCcw01 as RefreshCcw,
  RefreshCw01 as RefreshCw,
  SearchMd as Search,
  Send01 as Send,
  Settings01 as Settings,
  Settings02 as Settings2,
  Share01 as Share2,
  ShoppingBag01 as ShoppingBag,
  SlashCircle01 as ListX,
  Sliders03 as SlidersHorizontal,
  Star01 as Star,
  Stars01 as Sparkles,
  SwitchHorizontal01 as ArrowLeftRight,
  Table as FileSpreadsheet,
  Trash01 as Trash2,
  TrendDown01 as TrendingDown,
  TrendUp01 as TrendingUp,
  Upload01 as Upload,
  User01 as User,
  UserCircle as UserRound,
  VideoRecorder as MonitorPlay,
  Wallet01 as Wallet,
  XClose as X,
} from "@untitledui-pro/icons/line";
