import type { Superinvestor13fProfilePageData } from "@/lib/superinvestors/types";
import type { Berkshire13fComparisonPayload, SuperinvestorTransactionsPayload } from "@/lib/superinvestors/types";
import {
  getArkHoldingsComparison,
  getArkProfilePage,
  getArkQuarterlyTransactions,
  getBaillieGiffordHoldingsComparison,
  getBaillieGiffordProfilePage,
  getBaillieGiffordQuarterlyTransactions,
  getBerkshireHoldingsComparison,
  getBerkshireProfilePage,
  getBerkshireQuarterlyTransactions,
  getBlackrockHoldingsComparison,
  getBlackrockProfilePage,
  getBlackrockQuarterlyTransactions,
  getBridgewaterHoldingsComparison,
  getBridgewaterProfilePage,
  getBridgewaterQuarterlyTransactions,
  getCitadelHoldingsComparison,
  getCitadelProfilePage,
  getCitadelQuarterlyTransactions,
  getDailyJournalHoldingsComparison,
  getDailyJournalProfilePage,
  getDailyJournalQuarterlyTransactions,
  getFirstEagleHoldingsComparison,
  getFirstEagleProfilePage,
  getFirstEagleQuarterlyTransactions,
  getFisherHoldingsComparison,
  getFisherProfilePage,
  getFisherQuarterlyTransactions,
  getFundsmithHoldingsComparison,
  getFundsmithProfilePage,
  getFundsmithQuarterlyTransactions,
  getGmoHoldingsComparison,
  getGmoProfilePage,
  getGmoQuarterlyTransactions,
  getHimalayaHoldingsComparison,
  getHimalayaProfilePage,
  getHimalayaQuarterlyTransactions,
  getPershingSquareHoldingsComparison,
  getPershingSquareProfilePage,
  getPershingSquareQuarterlyTransactions,
  getPoint72HoldingsComparison,
  getPoint72ProfilePage,
  getPoint72QuarterlyTransactions,
  getPrimecapHoldingsComparison,
  getPrimecapProfilePage,
  getPrimecapQuarterlyTransactions,
  getRenaissanceTechnologiesHoldingsComparison,
  getRenaissanceTechnologiesProfilePage,
  getRenaissanceTechnologiesQuarterlyTransactions,
  getScionHoldingsComparison,
  getScionProfilePage,
  getScionQuarterlyTransactions,
  getTciFundHoldingsComparison,
  getTciFundProfilePage,
  getTciFundQuarterlyTransactions,
} from "@/lib/superinvestors/berkshire-13f";

export type SuperinvestorRegistryItem = {
  slug: string;
  managerName: string;
  fundNameOverride?: string;
  avatarSrc: string | null;
  /** Profile page: one cached 13F snapshot → holdings + transactions (no duplicate SEC loop). */
  loadProfilePage: () => Promise<Superinvestor13fProfilePageData>;
  /** Stock tab index: latest vs prior filing only (2 SEC filings). */
  load: () => Promise<Berkshire13fComparisonPayload>;
  loadTransactions: () => Promise<SuperinvestorTransactionsPayload>;
};

/** Tracked 13F filers shown on stock Superinvestors tab and `/superinvestors` profiles. */
export const SUPERINVESTOR_REGISTRY: SuperinvestorRegistryItem[] = [
  {
    slug: "berkshire-hathaway",
    managerName: "Warren Buffett",
    avatarSrc: "/superinvestors/warren-buffett.png",
    loadProfilePage: getBerkshireProfilePage,
    load: getBerkshireHoldingsComparison,
    loadTransactions: getBerkshireQuarterlyTransactions,
  },
  {
    slug: "bill-ackman",
    managerName: "Bill Ackman",
    avatarSrc: "/superinvestors/bill-ackman.png",
    loadProfilePage: getPershingSquareProfilePage,
    load: getPershingSquareHoldingsComparison,
    loadTransactions: getPershingSquareQuarterlyTransactions,
  },
  {
    slug: "terry-smith",
    managerName: "Terry Smith",
    avatarSrc: "/superinvestors/terry-smith.png",
    loadProfilePage: getFundsmithProfilePage,
    load: getFundsmithHoldingsComparison,
    loadTransactions: getFundsmithQuarterlyTransactions,
  },
  {
    slug: "michael-burry",
    managerName: "Michael Burry",
    avatarSrc: "/superinvestors/michael-burry.png",
    loadProfilePage: getScionProfilePage,
    load: getScionHoldingsComparison,
    loadTransactions: getScionQuarterlyTransactions,
  },
  {
    slug: "cathie-wood",
    managerName: "Cathie Wood",
    avatarSrc: "/superinvestors/cathie-wood.png",
    loadProfilePage: getArkProfilePage,
    load: getArkHoldingsComparison,
    loadTransactions: getArkQuarterlyTransactions,
  },
  {
    slug: "li-lu",
    managerName: "Li Lu",
    avatarSrc: "/superinvestors/li-lu.png",
    loadProfilePage: getHimalayaProfilePage,
    load: getHimalayaHoldingsComparison,
    loadTransactions: getHimalayaQuarterlyTransactions,
  },
  {
    slug: "ray-dalio",
    managerName: "Ray Dalio",
    avatarSrc: "/superinvestors/ray-dalio.png",
    loadProfilePage: getBridgewaterProfilePage,
    load: getBridgewaterHoldingsComparison,
    loadTransactions: getBridgewaterQuarterlyTransactions,
  },
  {
    slug: "ken-fisher",
    managerName: "Ken Fisher",
    avatarSrc: "/superinvestors/ken-fisher.png",
    loadProfilePage: getFisherProfilePage,
    load: getFisherHoldingsComparison,
    loadTransactions: getFisherQuarterlyTransactions,
  },
  {
    slug: "primecap-management",
    managerName: "PRIMECAP Management",
    avatarSrc: "/superinvestors/primecap-management.png",
    loadProfilePage: getPrimecapProfilePage,
    load: getPrimecapHoldingsComparison,
    loadTransactions: getPrimecapQuarterlyTransactions,
  },
  {
    slug: "ken-griffin",
    managerName: "Ken Griffin",
    avatarSrc: "/superinvestors/ken-griffin.png",
    loadProfilePage: getCitadelProfilePage,
    load: getCitadelHoldingsComparison,
    loadTransactions: getCitadelQuarterlyTransactions,
  },
  {
    slug: "charlie-munger",
    managerName: "Charlie Munger",
    fundNameOverride: "Daily Journal Holdings",
    avatarSrc: "/superinvestors/charlie-munger.png",
    loadProfilePage: getDailyJournalProfilePage,
    load: getDailyJournalHoldingsComparison,
    loadTransactions: getDailyJournalQuarterlyTransactions,
  },
  {
    slug: "blackrock",
    managerName: "BlackRock",
    avatarSrc: "/superinvestors/blackrock.png",
    loadProfilePage: getBlackrockProfilePage,
    load: getBlackrockHoldingsComparison,
    loadTransactions: getBlackrockQuarterlyTransactions,
  },
  {
    slug: "baillie-gifford",
    managerName: "Baillie Gifford",
    fundNameOverride: "Baillie Gifford & Co Holdings",
    avatarSrc: null,
    loadProfilePage: getBaillieGiffordProfilePage,
    load: getBaillieGiffordHoldingsComparison,
    loadTransactions: getBaillieGiffordQuarterlyTransactions,
  },
  {
    slug: "renaissance-technologies",
    managerName: "Jim Simons",
    fundNameOverride: "Renaissance Technologies Holdings",
    avatarSrc: "/superinvestors/jim-simons.png",
    loadProfilePage: getRenaissanceTechnologiesProfilePage,
    load: getRenaissanceTechnologiesHoldingsComparison,
    loadTransactions: getRenaissanceTechnologiesQuarterlyTransactions,
  },
  {
    slug: "point72",
    managerName: "Steven Cohen",
    fundNameOverride: "Point72 Asset Management Holdings",
    avatarSrc: "/superinvestors/steven-cohen.png",
    loadProfilePage: getPoint72ProfilePage,
    load: getPoint72HoldingsComparison,
    loadTransactions: getPoint72QuarterlyTransactions,
  },
  {
    slug: "first-eagle",
    managerName: "First Eagle Investments",
    fundNameOverride: "First Eagle Investment Management LLC",
    avatarSrc: null,
    loadProfilePage: getFirstEagleProfilePage,
    load: getFirstEagleHoldingsComparison,
    loadTransactions: getFirstEagleQuarterlyTransactions,
  },
  {
    slug: "chris-hohn",
    managerName: "Chris Hohn",
    fundNameOverride: "TCI Fund Management",
    avatarSrc: "/superinvestors/chris-hohn.png",
    loadProfilePage: getTciFundProfilePage,
    load: getTciFundHoldingsComparison,
    loadTransactions: getTciFundQuarterlyTransactions,
  },
  {
    slug: "jeremy-grantham",
    managerName: "Jeremy Grantham",
    fundNameOverride: "GMO Asset Management",
    avatarSrc: "/superinvestors/jeremy-grantham.png",
    loadProfilePage: getGmoProfilePage,
    load: getGmoHoldingsComparison,
    loadTransactions: getGmoQuarterlyTransactions,
  },
];
