/** Short profile copy for `/superinvestors/[slug]` headers (3–5 lines at 14px). */
export const SUPERINVESTOR_PROFILE_DESCRIPTIONS: Record<string, string> = {
  "berkshire-hathaway":
    "Warren Buffett has led Berkshire Hathaway since the 1960s, building it through insurance float, wholly owned businesses, and long-term public-equity stakes. The portfolio favors durable franchises, strong balance sheets, and managers he trusts to run operations with minimal interference. Buffett publishes a widely read annual letter and discloses U.S. equity holdings quarterly via SEC Form 13F. His approach blends Graham-style value discipline with quality-and-moat investing developed alongside Charlie Munger.",
  "bill-ackman":
    "Bill Ackman runs Pershing Square Capital Management, known for concentrated, high-conviction activist and long-only positions. He often takes sizable stakes in a small number of companies and pushes for operational, capital allocation, or governance changes when he sees a gap between price and intrinsic value. Pershing Square also offers a permanent-capital vehicle that can hold positions through multi-year theses. Filings provide a quarterly snapshot of the firm’s disclosed U.S. long book.",
  "terry-smith":
    "Terry Smith founded Fundsmith, a global equity manager built around a simple rule set: buy good businesses, don’t overpay, and do nothing unless fundamentals change. The strategy emphasizes high returns on capital, recurring revenue, and brands with pricing power rather than cyclical turnarounds. Fundsmith’s concentrated portfolio is disclosed through 13F filings for its U.S.-listed holdings. Smith is also known for blunt shareholder letters that stress quality over complexity.",
  "michael-burry":
    "Michael Burry founded Scion Asset Management and gained prominence for prescient calls ahead of the 2008 housing crisis, as chronicled in The Big Short. His style is deep fundamental research, often contrarian, with willingness to run concentrated books and use hedges or shorts when macro or sector risks build. Scion’s 13F snapshots show a typically small number of high-conviction equity positions. Burry communicates sparingly but his filings are closely watched for thematic shifts.",
  "cathie-wood":
    "Cathie Wood leads ARK Invest, focused on publicly traded companies she believes are leaders in disruptive innovation—areas such as genomics, robotics, energy storage, and next-generation internet platforms. ARK publishes research-heavy theses and runs themed ETFs that can move quickly when conviction or estimates change. The firm’s 13F book reflects overlapping holdings across those strategies. ARK’s high turnover and growth orientation make its quarterly filings a barometer for innovation sentiment.",
  "li-lu":
    "Li Lu manages Himalaya Capital Management and is often cited as an early bridge between Graham-and-Buffett value investing and modern China-focused capital allocation. He looks for understandable businesses with honest management, durable economics, and prices that offer a margin of safety. Himalaya’s disclosed U.S. portfolio is relatively concentrated and changes infrequently compared with many hedge funds. Li Lu is also known for a long association with Berkshire Hathaway’s investing culture.",
  "ray-dalio":
    "Ray Dalio founded Bridgewater Associates, one of the world’s largest macro-oriented investment firms. Bridgewater’s All Weather and Pure Alpha frameworks stress economic machine thinking, risk parity, and systematic decision rules applied across asset classes. Public 13F equity disclosures represent only a slice of the firm’s total assets but still show how macro views translate into large-cap U.S. positions. Dalio has written extensively on principles, debt cycles, and institutional decision-making.",
  "ken-fisher":
    "Ken Fisher built Fisher Investments into a global asset manager serving individual and institutional clients. His public commentary often emphasizes skepticism of consensus forecasts, small-cap and value tilts at times, and behavioral mistakes investors make around news cycles. Fisher’s 13F book tends to be broad and diversified relative to concentrated hedge funds. The firm’s filings are useful for tracking how a large advisory complex positions U.S. equities each quarter.",
  "primecap-management":
    "PRIMECAP Management is a Pasadena-based investment manager known for patient, research-intensive growth and value investing since the 1980s. The firm often builds positions slowly in companies where it sees long-run earnings power mispriced by the market. PRIMECAP manages Vanguard co-branded strategies alongside separate accounts, giving it a stable, long-horizon capital base. Its 13F shows a diversified but opinionated list of U.S. holdings across healthcare, tech, and industrials.",
  "ken-griffin":
    "Ken Griffin founded Citadel and Citadel Securities, combining multi-strategy hedge fund investing with a leading market-making business. Citadel’s hedge fund platform runs pods across equities, credit, commodities, and quantitative strategies with tight risk limits. Disclosed 13F equity holdings are only part of the picture but highlight large, liquid positions the firm is willing to show regulators. Griffin is among the most influential figures in modern market structure and electronic trading.",
  "charlie-munger":
    "Charlie Munger chaired Daily Journal Corporation and for decades was Warren Buffett’s investing partner at Berkshire Hathaway. Daily Journal’s public equity portfolio—disclosed via 13F—was famously concentrated in a handful of banks and a major consumer-tech holding. Munger advocated mental models, quality businesses, and avoiding unnecessary activity. His letters and talks stressed rationality, incentives, and the compounding power of owning great companies for very long periods.",
  "blackrock":
    "BlackRock is the world’s largest asset manager, built around index funds, ETFs, and Aladdin risk analytics used by institutions globally. Its active equity arms and model portfolios also take meaningful positions in large-cap U.S. names that appear in 13F filings. Scale and client flows mean changes can reflect both house views and fund mandate rebalancing. BlackRock’s quarterly disclosures offer a window into one of the most influential shareholders in public markets.",
  "baillie-gifford":
    "Baillie Gifford is an Edinburgh partnership known for long-duration growth investing in public and private markets. The firm seeks exceptional management teams building category-defining products, often tolerating volatility when the long runway remains intact. Its U.S. 13F book includes high-profile technology and consumer holdings tied to that philosophy. Baillie Gifford’s research culture emphasizes visiting companies, owner mindset, and multi-decade holding periods.",
  "renaissance-technologies":
    "Jim Simons founded Renaissance Technologies, pioneering quantitative investing with the Medallion Fund and other systematic strategies. Rentec’s models exploit statistical patterns across vast datasets, with human researchers and automated execution tightly integrated. Public 13F filings cover a subset of holdings and may not reflect the full complexity of its portfolios. The firm’s legacy reshaped how hedge funds use math, data, and execution technology.",
  "point72":
    "Steven Cohen leads Point72 Asset Management, a multi-manager platform evolved from SAC Capital with heavy emphasis on fundamental and systematic pods. Point72 combines internal teams, external portfolio managers, and data science to generate idiosyncratic equity and macro returns. Disclosed 13F positions highlight larger, more persistent U.S. equity lines alongside the broader pod ecosystem. Cohen is also known for art collecting and ownership of the New York Mets.",
  "first-eagle":
    "First Eagle Investment Management traces its roots to value-oriented investing with a focus on downside protection and global franchises. The firm is known for the First Eagle Global Fund philosophy: seek businesses that can survive stress, generate free cash, and compound through cycles. Its 13F snapshot shows U.S. listed positions that complement a wider global mandate. Analysts watch filings for shifts in gold miners, consumer staples, and international ADRs.",
  "chris-hohn":
    "Chris Hohn runs TCI Fund Management, a London-based activist investor with a small number of very large positions. TCI often engages boards on capital returns, cost discipline, and governance at portfolio companies it believes are underearning their potential. The strategy can hold names for years when management executes on agreed plans. Hohn’s 13F disclosures reveal a highly concentrated U.S. book dominated by a few mega-cap positions.",
  "jeremy-grantham":
    "Jeremy Grantham co-founded GMO, known for asset-allocation research, bubble commentary, and climate-focused investing in later years. GMO’s equity team historically emphasized mean reversion in margins and valuations, often leaning against crowded trades. The firm’s 13F filings show how those views translate into U.S. large-cap positions each quarter. Grantham’s essays on market extremes and resource limits remain influential among institutional allocators.",
  "seth-klarman":
    "Seth Klarman leads Baupost Group, a value-oriented firm famous for patience, cash when opportunities are scarce, and deep research into complex or unpopular situations. Baupost’s public equity book is typically concentrated and opportunistic rather than fully invested at all times. Quarterly 13F filings show the U.S.-listed portion of that book. Klarman’s Margin of Safety remains a touchstone for risk-aware value investing.",
  "carl-icahn":
    "Carl Icahn is a long-time activist investor who takes large stakes and presses for operational, capital-structure, or strategic change. Icahn Capital’s disclosed 13F positions are often concentrated in a handful of companies where engagement is central to the thesis. The book can include control-oriented holdings alongside liquid public equities. Filings are watched as a signal of activist campaigns and exits.",
  "david-tepper":
    "David Tepper founded Appaloosa Management (now Appaloosa LP), known for bold macro and credit calls as well as concentrated equity bets. The firm’s style blends deep fundamental work with a willingness to size up when conviction is high. Appaloosa’s 13F shows a relatively focused U.S. equity book that can shift with the cycle. Tepper’s track record through crises made him one of the most followed hedge-fund managers of his generation.",
  "david-einhorn":
    "David Einhorn founded Greenlight Capital and is known for rigorous long/short fundamental research and high-profile short theses. Current U.S. equity disclosures for the Greenlight complex file under DME Capital Management. The book is typically concentrated in a few dozen ideas rather than a closet index. Einhorn’s letters emphasize process, risk, and skepticism of consensus narratives.",
  "stanley-druckenmiller":
    "Stanley Druckenmiller runs Duquesne Family Office after decades as a top macro investor alongside George Soros and later independently. Duquesne’s 13F equity book is a public window into themes he is willing to hold in size, often with high turnover versus classic buy-and-hold value funds. Positions can span tech, energy, financials, and event-driven names. Markets still treat his filings as a high-signal read on macro and growth conviction.",
  "bill-gates":
    "The Gates Foundation Trust manages the endowment that supports the Bill & Melinda Gates Foundation’s philanthropic work. Its 13F portfolio historically favored a concentrated set of large, liquid U.S. equities rather than a diversified mutual-fund lookalike. Changes tend to be infrequent and deliberate. Filings are widely followed because of Gates’s profile and the Trust’s long-term capital base.",
  "tiger-global":
    "Chase Coleman leads Tiger Global Management, a growth-oriented firm spanning public equities and private technology investing. The public 13F book often concentrates in large-cap internet, software, and semiconductor names tied to long-duration growth theses. Position sizes can be large relative to many long-only peers. Tiger Global’s filings are a common benchmark for institutional growth positioning.",
  "chuck-akre":
    "Chuck Akre built Akre Capital Management around compounding high-quality businesses with strong reinvestment opportunities—often summarized as his “three-legged stool” of business, people, and reinvestment. The firm’s 13F book is concentrated in a modest number of franchises held for long stretches. Turnover is typically low when fundamentals remain intact. Akre’s letters stress valuation discipline without forcing activity.",
  "mohnish-pabrai":
    "Mohnish Pabrai manages Dalal Street with a Buffett-and-Munger-inspired checklist: buy simple businesses, insist on a margin of safety, and concentrate capital. The 13F book is often tiny—just a few high-conviction names—rather than a diversified fund. Pabrai’s annual meetings and cloning ideas are popular with individual value investors. Filings are watched for abrupt, concentrated bets.",
  "tom-gayner":
    "Tom Gayner is CEO of Markel Group and long oversaw its public equity portfolio in the insurance-float tradition associated with Berkshire-style capital allocation. Markel’s 13F shows a diversified but deliberate list of U.S. holdings built for long holding periods. The approach favors understandable businesses and patient ownership. Gayner’s commentary emphasizes culture, underwriting discipline, and compounding.",
  "guy-spier":
    "Guy Spier runs Aquamarine Capital, a Zurich-based value investor known for a Buffett-inspired, long-horizon approach and for The Education of a Value Investor. The firm’s U.S. equity book files under Aquamarine Zurich AG and is typically small and concentrated in high-quality franchises. Spier emphasizes process, temperament, and learning from other great investors. Quarterly 13F filings show a patient, low-turnover public book.",
};

export function getSuperinvestorProfileDescription(slug: string): string {
  return SUPERINVESTOR_PROFILE_DESCRIPTIONS[slug]?.trim() ?? "";
}
